### ISSUE TITLE
Missing licence - is this library part of public domain?

### ISSUE THREAD

**Issue by skrzyneckik** [reinaldoarrosi/QueryBuilder#1]
@reinaldoarrosi I know it's quite old project, but looks interesting and would be useful for my purposes. Is this library part of public domain? I would appreciate if you add an information about it.

**Comment by skrzyneckik** [comment]
@reinaldoarrosi If you want to share your work with the world, I would recommend Apache License, Version 2.0 - it's widely used across open source projects.

**Comment by reinaldoarrosi** [comment]
Sorry, never got around to adding a proper licensing for this project (it is lacking a bit of attention since I stopped working with Android). Feel free to use/modify this library for your own projects (even commercial ones). I'll add a license to it as soon as possible, probably MIT or Apache 2.0 as you sugested.

**Comment by skrzyneckik** [comment]
@reinaldoarrosi great to hear it, thanks!
